### ISSUE TITLE
Cannot pass bots the correct working directory

### ISSUE THREAD

**Issue by ErinvanderVeen** [ErinvanderVeen/Clone#2]

**Comment by camilstaps** [comment]
This is because the third argument of `runProcessIO` is [ignored in System.Process](https://cloogle.org/src/?lib=Platform#System.Process;icl;line=46) (as you perhaps found out already). [MR 43](https://gitlab.science.ru.nl/clean-and-itasks/clean-platform/merge_requests/43) on clean-platform addresses this.
